#ifndef CONSTANTS_VARS_FLAGS_H
#define CONSTANTS_VARS_FLAGS_H

#define FLAG_GUARANTEED_CAPTURE     2550
#define FLAG_NUZLOCKE_MODE          2551
#define FLAG_PORTA_PC_AVAILABLE     2552
#define FLAG_REPELLENT_ON           2553

#endif // CONSTANTS_VARS_FLAGS_H