#include "../include/types.h"
#include "../include/constants/sndseq.h"
#include "../include/constants/species.h"
#include "../include/constants/trainerclass.h"

// Table seems to combine animation in column 1 with music in column 2, 0xFFFF for no special animation

u16 MainMusicComboTable[][2] =
{
    [ANIM_MUSIC_COMBO_LEADER] = {0x2E, SEQ_GS_VS_GYMREADER},
    [ANIM_MUSIC_COMBO_ELITE_FOUR] = {0x2E, SEQ_GS_VS_GYMREADER_KANTO},
    [ANIM_MUSIC_COMBO_CHAMPION] = {0x2E, SEQ_GS_VS_CHAMP},

    [ANIM_MUSIC_COMBO_JOHTO_TRAINER] = {0xFFFF, SEQ_GS_VS_TRAINER},
    [ANIM_MUSIC_COMBO_JOHTO_WILD_THEME] = {0xFFFF, SEQ_GS_VS_NORAPOKE},
};

// format is one byte for trainer class, then one byte for combo (combo increments by 4 because each combo is four bytes long)

u8 TrainerClassToMusicCombo[][2] =
{
    {TRAINERCLASS_WHITNEY, ANIM_MUSIC_COMBO_LEADER*4},
    {TRAINERCLASS_RILEY, ANIM_MUSIC_COMBO_LEADER*4},
    {TRAINERCLASS_GARDENIA, ANIM_MUSIC_COMBO_LEADER*4},
    {TRAINERCLASS_BEDE, ANIM_MUSIC_COMBO_LEADER*4},
    {TRAINERCLASS_OLIVIA, ANIM_MUSIC_COMBO_LEADER*4},
    {TRAINERCLASS_ZINNIA, ANIM_MUSIC_COMBO_LEADER*4},
    {TRAINERCLASS_WALLACE, ANIM_MUSIC_COMBO_LEADER*4},
    {TRAINERCLASS_BENGA, ANIM_MUSIC_COMBO_LEADER*4},
    {TRAINERCLASS_SADA, ANIM_MUSIC_COMBO_ELITE_FOUR*4},
    {TRAINERCLASS_LEON, ANIM_MUSIC_COMBO_ELITE_FOUR*4},
    {TRAINERCLASS_DIANTHA, ANIM_MUSIC_COMBO_ELITE_FOUR*4},
    {TRAINERCLASS_TURO, ANIM_MUSIC_COMBO_ELITE_FOUR*4},
    {TRAINERCLASS_STEVEN, ANIM_MUSIC_COMBO_CHAMPION*4},
};

struct MonBattleMusic
{
    u16 species:10;
    u16 combo:6;
};

struct MonBattleMusic PokemonBattleMusic[] =
{
};

struct TrainerMusic
{
    u16 class;
    u16 music1;
    u16 music2;
};

struct TrainerMusic sTrainerEncounterMusicParam[] = // cues which music sequence occurs upon eyes meeting
{
    {.class = TRAINERCLASS_NONE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_OAK, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BIANCA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_TIERNO, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_WALLY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_TCHEREN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_LILLIE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MILO, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ILIMA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_LISIA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_VIOLA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BARRY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ERIKA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_TULIP, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MALLOW, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BROCK, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_WHITNEY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BEA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_NANU, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_FLANNERY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ROXIE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_SURGE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ROARK, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BYRON, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ALLISTER, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BRYCEN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_RILEY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_CHUCK, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ELESA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_FANTINA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_CHERYL, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_KABU, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BURGH, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BRASSIUS, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_JANINE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BUGSY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_GARDENIA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_OPAL, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_JASMINE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_VALERIE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_LIZA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_KORRINA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_OLYMPIA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MARSHAL, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_NORMAN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_SABRINA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_PALMER, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BEDE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_POPPY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BRANDON, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_RIKA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ROXANNE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_LENORA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MOLAYNE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_AARUNE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_DRASNA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_AARON, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ACEROLA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_OLIVIA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MARNIE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_LARRY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_NOLAND, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_CANDICE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_CAITLIN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_GRUSHA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BURNET, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_KOGA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_SPENSER, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_WINONA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_ZINNIA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_PHOEBE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_JUAN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MISTY, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_NESSA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_GUZMA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_LORELEI, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MARLON, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_CLAIR, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_SIEBOLD, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_CLEMONT, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_HAU, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_VOLKNER, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_WALLACE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BERTHA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_AGATHA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BLAINE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BUCK, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_KIAWE, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_RAIHAN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MALVA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_GREEN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_KAREN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_FLINT, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_GIOVANNI, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_N, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_BENGA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_SADA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_LEON, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_DIANTHA, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_TURO, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_STEVEN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
};
